#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$(uname -s)" == "Linux" ]]; then
    if [[ ! -f /proc/self/uid_map ]]; then
      # TODO linux client needs this file
      return 0
    fi
  fi

  if [[ "$($shome/script/version | jq -r '.concourse')" != "$CONCOURSE_VERSION" ]]; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.fly')" != "$CONCOURSE_VERSION" ]]; then
    return 1
  fi

  return 0
}

main "$@"
