#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_concourse="0.0.1"
  jq -n --arg concourse "$ver_concourse" '{concourse: $concourse}'
}

version "$@"
